### ISSUE TITLE
How to use Arc<> in new_service_def()

### ISSUE THREAD

**Issue by VenusHu** [stepancheg/grpc-rust#101]
Hi, I'm new to rust, so I have a problem bothering me, hoping to get help.
I define a struct called Peer, wrapped it using Arc, then use a new thread to start PRC server:

```
fn start_server(p: Arc<Peer>) {
...
server.add_service(PeerSrvServer::new_service_def(p));
...
}
```

then I get compile error: 
```
the trait bound `std::sync::Arc<demo_with_grpc::peer::Peer>: demo_with_grpc::peerpb_grpc::PeerSrv` is not satisfied
```

So what's the correct way to write the code? 
Many thanks!

**Comment by thedodd** [comment]
You are getting that error because only your underlying `Peer` struct implements the interface that you are needing. `Arc<Peer>` is a different type altogether, and according to the compiler, does not implement that interface. 

A way to work around this:
- pass only the strict instance to your function mentioned above. 
- if you still need to share that instance with other threads (if so, why?) then wrap it in an Arc after the function call.

**Comment by VenusHu** [comment]
Solved it. 
The reason why I need to share the instance with other threads is that my instance needs to be both rpc client and server. I'm constructing a p2p system.

**Comment by stepancheg** [comment]
@thedodd thank you for help answering!

**Comment by thedodd** [comment]
Absolutely.
