### ISSUE TITLE
mutable implementation of service trait

### ISSUE THREAD

**Issue by hamersaw** [stepancheg/grpc-rust#9]
It seems to me that structs implementing a service trait often need to be mutable, for example in the route-guide protobuf example. The trait requires a non-mutable reference to self. It's an interesting problem as to when to make the reference mutable, has there been any thought put into this? What does the timeline look like?

**Comment by stepancheg** [comment]
Generally, service implementation can be executed concurrently (not possible yet in async version of service, but sync version is executed in the thread pool), so it not possible to make a reference to self mutable safely.

Standard solution to this problem is to wrap your mutable part of the state into something like `Arc<Mutex<State>>` and take a lock during the change of the state.
